export default {
    Homepage:'/',
    ProductPage: '/productpage',
    CartPage: '/cartpage',
    ProductDetail: '/productdetail',
    Login: '/login',
    Signup: '/signup',
    Address: '/signup/address',
    Order: '/order',
    confirmOrder: '/confirmOrder',
    myOrder: '/myorders',
    myCards: '/mycards',
    forgetPassword: '/forgetpassword',
    codeVerification: '/verifycode',
    newPassword: '/newpassword',
    profile: '/profile',
    address:'address',
    NotFound:'*',
};